Update node-api with vote extrinsic.
logion-network/logion-api pull request #91
Opened 2023-01-19 14:00 UTC by benoitdevos

logion-network/logion-internal#725

2023-01-19 14:11 UTC, gdethier requested changes
I think something is broken in the generation code. Let's discuss.

2023-01-19 14:11 UTC, gdethier commented on packages/crossmint/package.json
> +  "version": "0.1.7-1",
I think you could have just bumped the micro (no code change) but it's OK.

2023-01-19 14:11 UTC, gdethier commented on packages/client/package.json
> +  "version": "0.19.0-1",
I think you could have just bumped the micro (no code change) but it's OK.

2023-01-19 14:11 UTC, gdethier commented on packages/extension/package.json
> +  "version": "0.5.5-1",
I think you could have just bumped the micro (no code change) but it's OK.

2023-01-19 14:11 UTC, gdethier commented on packages/node-api/src/interfaces/augment-types.ts
> -import type { BeefyKey, FullIdentification, IdentificationTuple, Keys, MembershipProof, SessionIndex, SessionKeys1, SessionKeys10, SessionKeys10B, SessionKeys2, SessionKeys3, SessionKeys4, SessionKey
I think there is something broken here...

2023-01-19 14:11 UTC, gdethier commented on packages/node-api/src/interfaces/augment-types.ts
> +import type { AuthIndex, AuthoritySignature, Heartbeat, HeartbeatTo244, OpaqueMultiaddr, OpaqueNetworkState, OpaquePeerId } from '@polkadot/types/interfaces/imOnline';
This is potentially a problem.

2023-01-19 14:11 UTC, gdethier commented on packages/node-api/src/interfaces/augment-types.ts
> -    CollectionSize: CollectionSize;
This is not normal.

2023-01-19 17:14 UTC, benoitdevos commented on packages/node-api/src/interfaces/augment-types.ts
> +import type { AuthIndex, AuthoritySignature, Heartbeat, HeartbeatTo244, OpaqueMultiaddr, OpaqueNetworkState, OpaquePeerId } from '@polkadot/types/interfaces/imOnline';
Fixed

2023-01-19 17:14 UTC, benoitdevos commented on packages/node-api/src/interfaces/augment-types.ts
> -    CollectionSize: CollectionSize;
Manually fixed.

2023-01-20 07:18 UTC, gdethier requested changes
There are still some missing overrides.

2023-01-20 07:18 UTC, gdethier commented on packages/node-api/src/interfaces/augment-types.ts
> +import type { CollectionItem, CollectionItemFile, CollectionItemId, CollectionItemToken, CollectionSize, File, HostData, LegalOfficerCaseOf, LegalOfficerData, LoAuthorityListStorageVersion, LocId, Lo
Default type definitions are back, but we are still lacking the overrides for runtime and session. See removed imports.

2023-01-20 07:18 UTC, gdethier commented on packages/node-api/src/interfaces/augment-types.ts
> -    Requester: Requester;
Maybe this has no impact but I don't see why it should be removed.

2023-01-20 08:56 UTC, gdethier approved these changes
:+1:

2023-01-20 08:56 UTC, merged